name: Publish Docker image
description: Publish Docker image and sends it to monitor by snyk.io
inputs:
  TAG:
    description: "Tag"
    required: true
  QUAY_SNYK_INTEGRATION_ID:
    description: "Tag"
    required: true
  SNYK_ORG_ID:
    description: "Tag"
    required: true
  SNYK_TOKEN:
    description: "Tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create manifest for current tag
      run: |
        docker manifest create ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ inputs.TAG }} \
        --amend ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_NAME }}:amd64 \
        --amend ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_NAME }}:arm64
      shell: bash

    - name: Publish manifest for current tag
      run: docker manifest push ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ inputs.TAG }}
      shell: bash

    - name: Add snyk
      run: |
        curl --location 'https://snyk.io/api/v1/org/${{ secrets.SNYK_ORG_ID }}/integrations/${{ secrets.QUAY_SNYK_INTEGRATION_ID }}/import' \
        --header 'Authorization: token ${{ secrets.SNYK_TOKEN }}' \
        --header 'Content-Type: application/json; charset=utf-8' \
        --data '{
          "target": {
            "name": "${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ inputs.TAG }}"
          }
        }'
      shell: bash
