name: Build and scan Docker image
description: Builds Dockerfile and scans it with snyk.io
inputs:
  swagger-ui-version:
    description: "Version on SwaggerUI dependency"
    required: true
  image-name:
    description: "Name of Image"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get swagger-ui repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: swagger-api/swagger-ui
        ref: refs/tags/${{ inputs.swagger-ui-version }}
        path: ./swagger-ui

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          network=host
        platforms: linux/amd64,linux/arm64

    - name: Run local registry
      run: docker run -d --name local --network=host registry:2
      shell: bash

    - name: Patch Dockerfile of swagger-ui docker image
      run: sed -i "s/nginx:1.23.2-alpine/nginx:alpine/; s/nodejs>=16.17.1-r0/nodejs>=18.14.1-r0/" ./swagger-ui/Dockerfile
      shell: bash

    - name: Build and push swagger-ui to local registry
      run: docker buildx build --push --provenance=false --network=host --platform linux/amd64,linux/arm64 -t localhost:5000/swagger-ui:${{ inputs.swagger-ui-version }} ./swagger-ui/.
      shell: bash

    - name: Build dockerimage
      uses: docker/build-push-action@v4
      with:
        provenance: false
        platforms: linux/amd64,linux/arm64
        build-args: |
          SWAGGER_UI_IMAGE=swagger-ui:${{ inputs.swagger-ui-version }}
          LOCAL_REGISTRY=localhost:5000/
        tags: |
          ${{ inputs.image-name }}
