name: Build image
description: Build docker image
runs:
  using: "composite"
  steps:
    - name: Print envs
      run: printenv
      shell: bash

    - name: Get swagger-ui repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: swagger-api/swagger-ui
        ref: refs/tags/${{ vars.SWAGGER_UI_VERSION }}
        path: ./swagger-ui

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          network=host
        platforms: linux/amd64,linux/arm64

    - name: Run local registry
      run: docker run -d --name ${{ vars.TEMP_LOCAL_REGISTRY_NAME }} --network=host registry:2
      shell: bash

    - name: Patch Dockerfile of swagger-ui docker image
      run: sed -i "s/nginx:1.23.2-alpine/nginx:alpine/; s/nodejs>=16.17.1-r0/nodejs>=18.14.1-r0/" ./swagger-ui/Dockerfile
      shell: bash

    - name: Build and push swagger-ui to local registry
      run: docker buildx build --push --provenance=false --network=host --platform linux/amd64,linux/arm64 -t localhost:5000/swagger-ui:${{ vars.SWAGGER_UI_VERSION }} ./swagger-ui/.
      shell: bash
